#!/usr/bin/env python3
from pathlib import Path

vox = Path("upstream/tmc/port/port_voxel.cpp")
src = vox.read_text(encoding="utf-8")

# Non-GPU builds still need a C-callable stub because movement.c references it.
stub_anchor = """void Port_Voxel_RequestShot(const char*) {
}
"""
stub_repl = stub_anchor + """extern "C" bool Port_Voxel_PlayerSolidAtPixel(int, int, int, int) {
    return false;
}
"""
if stub_anchor not in src:
    raise SystemExit("voxel non-GPU stub anchor not found")
src = src.replace(stub_anchor, stub_repl, 1)

# Shared rendered-world collision/height state.  This is generated by BuildMap()
# itself, so rendering and player collision cannot classify the same tile differently.
state_anchor = """const AreaShapes* sBuildShapes = nullptr; /* CurrentShapes() for the BuildMap in progress */
"""
state_repl = state_anchor + """
static Uint8 sVoxelFrontFace[64 * 64] = {};
static float sVoxelHeight[64 * 64] = {};
static int sVoxelW = 0, sVoxelH = 0;
static int sVoxelOriginX = 0, sVoxelOriginY = 0;
static int sVoxelArea = -1;
static bool sVoxelCollisionValid = false;

float WorldHeightAt(float worldX, float worldZ) {
    if (!sVoxelCollisionValid || sVoxelArea != gRoomControls.area ||
        sVoxelOriginX != gRoomControls.origin_x || sVoxelOriginY != gRoomControls.origin_y)
        return 0.0f;
    const int tx = (int)std::floor((worldX - (float)sVoxelOriginX) / 16.0f);
    const int ty = (int)std::floor((worldZ - (float)sVoxelOriginY) / 16.0f);
    if (tx < 0 || ty < 0 || tx >= sVoxelW || ty >= sVoxelH)
        return 0.0f;
    return sVoxelHeight[ty * 64 + tx];
}
"""
if state_anchor not in src:
    raise SystemExit("voxel shared-state anchor not found")
src = src.replace(state_anchor, state_repl, 1)

# Invalidate stale occupancy while a new room geometry build is in progress.
build_anchor = """void BuildMap(void) {
    int n = 0;
    sBuildShapes = CurrentShapes();
"""
build_repl = """void BuildMap(void) {
    int n = 0;
    sVoxelCollisionValid = false;
    sBuildShapes = CurrentShapes();
"""
if build_anchor not in src:
    raise SystemExit("BuildMap anchor not found")
src = src.replace(build_anchor, build_repl, 1)

# Publish the exact solid classification and generated top heights once pass 1
# has finished. Solid rendered blocks are full-tile collision in 3D mode; this
# intentionally tightens partial native collision only while voxel view is active.
height_anchor = """    auto hAt = [&](int x, int b) { return inRoom(x, b) ? hmap[b * 64 + x] : 0.0f; };

    /* ---- pass 2: draw ---- */
"""
height_repl = """    sVoxelW = W;
    sVoxelH = H;
    sVoxelOriginX = gRoomControls.origin_x;
    sVoxelOriginY = gRoomControls.origin_y;
    sVoxelArea = gRoomControls.area;
    std::memset(sVoxelFrontFace, 0, sizeof(sVoxelFrontFace));
    std::memset(sVoxelHeight, 0, sizeof(sVoxelHeight));
    for (int cy = 0; cy < H; ++cy)
        for (int cx = 0; cx < W; ++cx)
            sVoxelHeight[cy * 64 + cx] = hmap[cy * 64 + cx];

    /* Supplemental collision follows the wall face that is actually rendered,
     * not every bottom-layer solid tile. This avoids blocking legitimate
     * top-layer/stair movement while still keeping Link out of a tilted wall. */
    for (const Run& rn : runs)
        if (rn.x >= 0 && rn.x < W && rn.yb >= 0 && rn.yb < H)
            sVoxelFrontFace[rn.yb * 64 + rn.x] = 1;

    sVoxelCollisionValid = true;

    auto hAt = [&](int x, int b) { return inRoom(x, b) ? hmap[b * 64 + x] : 0.0f; };

    /* ---- pass 2: draw ---- */
"""
if height_anchor not in src:
    raise SystemExit("voxel hAt anchor not found")
src = src.replace(height_anchor, height_repl, 1)

# Lift all world entity billboards and decals to the rendered floor/plateau
# beneath their feet. This keeps Link/NPCs/shadows aligned with tilted geometry.
sprite_anchor = """        const float x0 = o.x + scrollX, x1 = x0 + o.w;
        const int sy0 = o.y, sy1 = sy0 + o.h;
        const float elev = tag.layer == 2 ? kTopLayerLift : 0.0f;
        float c[4][3];
"""
sprite_repl = """        const float x0 = o.x + scrollX, x1 = x0 + o.w;
        const int sy0 = o.y, sy1 = sy0 + o.h;
        const float entityFootZ = (float)std::max<int>(tag.groundY, sy1) + scrollY;
        const float entityCenterX = (x0 + x1) * 0.5f;
        const float groundHeight = WorldHeightAt(entityCenterX + gRoomControls.origin_x,
                                                  entityFootZ + gRoomControls.origin_y);
        const float layerHeight = tag.layer == 2 ? kTopLayerLift : 0.0f;
        const float elev = tag.kind == PORT_VOXEL_OAM_ENTITY ? std::max(groundHeight, layerHeight) : layerHeight;
        float c[4][3];
"""
if sprite_anchor not in src:
    raise SystemExit("voxel entity elevation anchor not found")
src = src.replace(sprite_anchor, sprite_repl, 1)

# Public C ABI queried by the native player tile-collision path.
public_anchor = """int Port_Voxel_CurrentArea(void) {
    return SceneApplicable() ? gRoomControls.area : -1;
}
"""
public_repl = """extern "C" bool Port_Voxel_PlayerSolidAtPixel(int worldX, int worldY, int collisionLayer, int direction) {
    if (!Port_Config_GetVoxelView() || !sVoxelCollisionValid ||
        sVoxelArea != gRoomControls.area ||
        sVoxelOriginX != gRoomControls.origin_x || sVoxelOriginY != gRoomControls.origin_y)
        return false;

    /* Supplemental voxel collision only applies when the native bottom layer
     * participates. Top-only movement (raised platforms/stairs) remains fully
     * native. COL_LAYER_BOTH is allowed during transitions so the barrier
     * cannot disappear for a frame while Link walks north into a wall. */
    if ((collisionLayer & 1) == 0)
        return false;

    const int relX = worldX - sVoxelOriginX;
    const int relY = worldY - sVoxelOriginY;
    if (relX < 0 || relY < 0)
        return false;
    const int tx = relX >> 4;
    const int ty = relY >> 4;
    if (tx < 0 || ty < 0 || tx >= sVoxelW || ty >= sVoxelH)
        return false;

    /* The source wall tile itself is closed in 3D. */
    if (sVoxelFrontFace[ty * 64 + tx])
        return true;

    /* Direction-aware south-side wall clearance.
     *
     * North/NW/NE movement is the case where Link visually enters a tilted
     * camera-facing wall before the native 2D collision probe reaches the
     * source tile. Add a small barrier only while approaching that wall from
     * below. This avoids invisible side/stair collision in the other directions. */
    const int dir = direction & 0x1F;
    const bool movingNorth = (dir <= 4) || (dir >= 28);
    if (movingNorth && ty > 0 && sVoxelFrontFace[(ty - 1) * 64 + tx]) {
        const float pitch = std::abs((float)Port_Config_GetVoxelPitch()) * 3.14159265f / 180.0f;
        const int clearance = std::clamp(6 + (int)std::ceil(std::sin(pitch) * 10.0f), 8, 15);
        if ((relY & 15) < clearance)
            return true;
    }
    return false;
}

int Port_Voxel_CurrentArea(void) {
    return SceneApplicable() ? gRoomControls.area : -1;
}
"""
if public_anchor not in src:
    raise SystemExit("voxel public API anchor not found")
src = src.replace(public_anchor, public_repl, 1)

vox.write_text(src, encoding="utf-8")

# C header: expose only the collision query to C gameplay code.
hdr = Path("upstream/tmc/port/port_voxel.h")
h = hdr.read_text(encoding="utf-8")
h_anchor = """void Port_Voxel_RequestShot(const char* path);

#ifdef __cplusplus
}
"""
h_repl = """void Port_Voxel_RequestShot(const char* path);
/* 3D-mode occupancy generated from the exact geometry BuildMap rendered.
 * Native movement keeps its original collision and ORs this only for Link. */
bool Port_Voxel_PlayerSolidAtPixel(int worldX, int worldY, int collisionLayer, int direction);

#ifdef __cplusplus
}
"""
if h_anchor not in h:
    raise SystemExit("voxel header C ABI anchor not found")
h = h.replace(h_anchor, h_repl, 1)
hdr.write_text(h, encoding="utf-8")

# Player movement: preserve every original collision shape, but when 3D mode
# renders a tile as a closed solid block/prop, treat that tile as solid too.
move = Path("upstream/tmc/src/movement.c")
m = move.read_text(encoding="utf-8")
inc_old = """#ifdef PC_PORT
#include "player.h"  /* gPlayerEntity for the debug noclip hook */
extern int Port_Debug_NoclipEnabled(void);
#endif
"""
inc_new = """#ifdef PC_PORT
#include "player.h"  /* gPlayerEntity for the debug noclip hook */
#include "port_voxel.h"
extern int Port_Debug_NoclipEnabled(void);
#endif
"""
if inc_old not in m:
    raise SystemExit("movement PC_PORT include block not found")
m = m.replace(inc_old, inc_new, 1)

calc = m.index("void CalculateEntityTileCollisions(Entity* this, u32 direction, u32 collisionType) {")
if calc < 0:
    raise SystemExit("CalculateEntityTileCollisions not found")

helper = """#ifdef PC_PORT
static bool32 Port_EntityTileCollision(Entity* entity, const u8* collisionData, s32 x, s32 y, u32 collisionType, u32 direction) {
    bool32 hit = IsTileCollision(collisionData, x, y, collisionType);
    if (!hit && entity == &gPlayerEntity.base && Port_Voxel_PlayerSolidAtPixel(x, y, entity->collisionLayer, direction))
        return TRUE;
    return hit;
}
#else
static bool32 Port_EntityTileCollision(Entity* entity, const u8* collisionData, s32 x, s32 y, u32 collisionType, u32 direction) {
    (void)entity;
    (void)direction;
    return IsTileCollision(collisionData, x, y, collisionType);
}
#endif

"""
m = m[:calc] + helper + m[calc:]
calc = m.index("void CalculateEntityTileCollisions(Entity* this, u32 direction, u32 collisionType) {")
end = m.index("\n}\n\nbool32 ProcessMovementInternal", calc) + 3
block = m[calc:end]
block2 = block.replace("IsTileCollision(collisionData,", "Port_EntityTileCollision(this, collisionData,")
block2 = block2.replace(", collisionType)", ", collisionType, direction)")
if block == block2:
    raise SystemExit("no tile-collision calls replaced")
m = m[:calc] + block2 + m[end:]
move.write_text(m, encoding="utf-8")

print("Aligned northward 3D wall-plane collision with native layers and rendered height")
