#!/usr/bin/env python3
from pathlib import Path

vox = Path("upstream/tmc/port/port_voxel.cpp")
src = vox.read_text(encoding="utf-8")

# Non-GPU builds still need a C-callable stub because movement.c references it.
stub_anchor = """void Port_Voxel_RequestShot(const char*) {
}
"""
stub_repl = stub_anchor + """extern "C" bool Port_Voxel_PlayerSolidAtPixel(int, int) {
    return false;
}
"""
if stub_anchor not in src:
    raise SystemExit("voxel non-GPU stub anchor not found")
src = src.replace(stub_anchor, stub_repl, 1)

# Shared rendered-world collision/height state.  This is generated by BuildMap()
# itself, so rendering and player collision cannot classify the same tile differently.
state_anchor = """const AreaShapes* sBuildShapes = nullptr; /* CurrentShapes() for the BuildMap in progress */
"""
state_repl = state_anchor + """
static Uint8 sVoxelSolid[64 * 64] = {};
static float sVoxelHeight[64 * 64] = {};
static int sVoxelW = 0, sVoxelH = 0;
static int sVoxelOriginX = 0, sVoxelOriginY = 0;
static int sVoxelArea = -1;
static bool sVoxelCollisionValid = false;

float WorldHeightAt(float worldX, float worldZ) {
    if (!sVoxelCollisionValid || sVoxelArea != gRoomControls.area ||
        sVoxelOriginX != gRoomControls.origin_x || sVoxelOriginY != gRoomControls.origin_y)
        return 0.0f;
    const int tx = (int)std::floor((worldX - (float)sVoxelOriginX) / 16.0f);
    const int ty = (int)std::floor((worldZ - (float)sVoxelOriginY) / 16.0f);
    if (tx < 0 || ty < 0 || tx >= sVoxelW || ty >= sVoxelH)
        return 0.0f;
    return sVoxelHeight[ty * 64 + tx];
}
"""
if state_anchor not in src:
    raise SystemExit("voxel shared-state anchor not found")
src = src.replace(state_anchor, state_repl, 1)

# Invalidate stale occupancy while a new room geometry build is in progress.
build_anchor = """void BuildMap(void) {
    int n = 0;
    sBuildShapes = CurrentShapes();
"""
build_repl = """void BuildMap(void) {
    int n = 0;
    sVoxelCollisionValid = false;
    sBuildShapes = CurrentShapes();
"""
if build_anchor not in src:
    raise SystemExit("BuildMap anchor not found")
src = src.replace(build_anchor, build_repl, 1)

# Publish the exact solid classification and generated top heights once pass 1
# has finished. Solid rendered blocks are full-tile collision in 3D mode; this
# intentionally tightens partial native collision only while voxel view is active.
height_anchor = """    auto hAt = [&](int x, int b) { return inRoom(x, b) ? hmap[b * 64 + x] : 0.0f; };

    /* ---- pass 2: draw ---- */
"""
height_repl = """    sVoxelW = W;
    sVoxelH = H;
    sVoxelOriginX = gRoomControls.origin_x;
    sVoxelOriginY = gRoomControls.origin_y;
    sVoxelArea = gRoomControls.area;
    std::memset(sVoxelSolid, 0, sizeof(sVoxelSolid));
    std::memset(sVoxelHeight, 0, sizeof(sVoxelHeight));
    for (int cy = 0; cy < H; ++cy)
        for (int cx = 0; cx < W; ++cx) {
            const int ctile = cy * 64 + cx;
            sVoxelSolid[ctile] = (kind[ctile] == 1 || kind[ctile] == 2) ? 1 : 0;
            sVoxelHeight[ctile] = hmap[ctile];
        }
    sVoxelCollisionValid = true;

    auto hAt = [&](int x, int b) { return inRoom(x, b) ? hmap[b * 64 + x] : 0.0f; };

    /* ---- pass 2: draw ---- */
"""
if height_anchor not in src:
    raise SystemExit("voxel hAt anchor not found")
src = src.replace(height_anchor, height_repl, 1)

# Lift all world entity billboards and decals to the rendered floor/plateau
# beneath their feet. This keeps Link/NPCs/shadows aligned with tilted geometry.
sprite_anchor = """        const float x0 = o.x + scrollX, x1 = x0 + o.w;
        const int sy0 = o.y, sy1 = sy0 + o.h;
        const float elev = tag.layer == 2 ? kTopLayerLift : 0.0f;
        float c[4][3];
"""
sprite_repl = """        const float x0 = o.x + scrollX, x1 = x0 + o.w;
        const int sy0 = o.y, sy1 = sy0 + o.h;
        const float entityFootZ = (float)std::max<int>(tag.groundY, sy1) + scrollY;
        const float entityCenterX = (x0 + x1) * 0.5f;
        const float groundHeight = WorldHeightAt(entityCenterX + gRoomControls.origin_x,
                                                  entityFootZ + gRoomControls.origin_y);
        const float elev = groundHeight + (tag.layer == 2 ? kTopLayerLift : 0.0f);
        float c[4][3];
"""
if sprite_anchor not in src:
    raise SystemExit("voxel entity elevation anchor not found")
src = src.replace(sprite_anchor, sprite_repl, 1)

# Public C ABI queried by the native player tile-collision path.
public_anchor = """int Port_Voxel_CurrentArea(void) {
    return SceneApplicable() ? gRoomControls.area : -1;
}
"""
public_repl = """extern "C" bool Port_Voxel_PlayerSolidAtPixel(int worldX, int worldY) {
    if (!Port_Config_GetVoxelView() || !sVoxelCollisionValid ||
        sVoxelArea != gRoomControls.area ||
        sVoxelOriginX != gRoomControls.origin_x || sVoxelOriginY != gRoomControls.origin_y)
        return false;

    const int tx = (worldX - sVoxelOriginX) >> 4;
    const int ty = (worldY - sVoxelOriginY) >> 4;
    if (tx < 0 || ty < 0 || tx >= sVoxelW || ty >= sVoxelH)
        return false;
    return sVoxelSolid[ty * 64 + tx] != 0;
}

int Port_Voxel_CurrentArea(void) {
    return SceneApplicable() ? gRoomControls.area : -1;
}
"""
if public_anchor not in src:
    raise SystemExit("voxel public API anchor not found")
src = src.replace(public_anchor, public_repl, 1)

vox.write_text(src, encoding="utf-8")

# C header: expose only the collision query to C gameplay code.
hdr = Path("upstream/tmc/port/port_voxel.h")
h = hdr.read_text(encoding="utf-8")
h_anchor = """void Port_Voxel_RequestShot(const char* path);

#ifdef __cplusplus
}
"""
h_repl = """void Port_Voxel_RequestShot(const char* path);
/* 3D-mode occupancy generated from the exact geometry BuildMap rendered.
 * Native movement keeps its original collision and ORs this only for Link. */
bool Port_Voxel_PlayerSolidAtPixel(int worldX, int worldY);

#ifdef __cplusplus
}
"""
if h_anchor not in h:
    raise SystemExit("voxel header C ABI anchor not found")
h = h.replace(h_anchor, h_repl, 1)
hdr.write_text(h, encoding="utf-8")

# Player movement: preserve every original collision shape, but when 3D mode
# renders a tile as a closed solid block/prop, treat that tile as solid too.
move = Path("upstream/tmc/src/movement.c")
m = move.read_text(encoding="utf-8")
inc_old = """#ifdef PC_PORT
#include "player.h"  /* gPlayerEntity for the debug noclip hook */
extern int Port_Debug_NoclipEnabled(void);
#endif
"""
inc_new = """#ifdef PC_PORT
#include "player.h"  /* gPlayerEntity for the debug noclip hook */
#include "port_voxel.h"
extern int Port_Debug_NoclipEnabled(void);
#endif
"""
if inc_old not in m:
    raise SystemExit("movement PC_PORT include block not found")
m = m.replace(inc_old, inc_new, 1)

calc = m.index("void CalculateEntityTileCollisions(Entity* this, u32 direction, u32 collisionType) {")
if calc < 0:
    raise SystemExit("CalculateEntityTileCollisions not found")

helper = """#ifdef PC_PORT
static bool32 Port_EntityTileCollision(Entity* entity, const u8* collisionData, s32 x, s32 y, u32 collisionType) {
    bool32 hit = IsTileCollision(collisionData, x, y, collisionType);
    if (!hit && entity == &gPlayerEntity.base && Port_Voxel_PlayerSolidAtPixel(x, y))
        return TRUE;
    return hit;
}
#else
static bool32 Port_EntityTileCollision(Entity* entity, const u8* collisionData, s32 x, s32 y, u32 collisionType) {
    (void)entity;
    return IsTileCollision(collisionData, x, y, collisionType);
}
#endif

"""
m = m[:calc] + helper + m[calc:]
calc = m.index("void CalculateEntityTileCollisions(Entity* this, u32 direction, u32 collisionType) {")
end = m.index("\n}\n\nbool32 ProcessMovementInternal", calc) + 3
block = m[calc:end]
block2 = block.replace("IsTileCollision(collisionData,", "Port_EntityTileCollision(this, collisionData,")
if block == block2:
    raise SystemExit("no tile-collision calls replaced")
m = m[:calc] + block2 + m[end:]
move.write_text(m, encoding="utf-8")

print("Unified 3D rendered solids/heights with Link collision and entity elevation")
